#include <stdio.h>
#include <math.h>

int main() {
    float a, b, c, delta, x1, x2;

    // Nhập các hệ số của phương trình
    printf("Nhap a, b, c: ");
    scanf("%f %f %f", &a, &b, &c);

    // Tính delta
    delta = b * b - 4 * a * c;

    // Kiểm tra các trường hợp
    if (delta < 0) {
        printf("Phuong trinh vo nghiem");
    } else if (delta == 0) {
        x1 = -b / (2 * a);
        printf("Phuong trinh co nghiem kep x = %f", x1);
    } else {
        x1 = (-b + sqrt(delta)) / (2 * a);
        x2 = (-b - sqrt(delta)) / (2 * a);
        printf("Phuong trinh co 2 nghiem phan biet: x1 = %f va x2 = %f", x1, x2);
    }

    return 0;
}
